### ISSUE TITLE
minecraft doesn t launch with minecraft capes mod installed

### ISSUE THREAD

**Issue by Imayreportbugs** [tr7zw/WaveyCapes#2]
![image](https://user-images.githubusercontent.com/85785009/131731774-af3fcc3a-3355-4e2c-84a4-ccd5354d2739.png)
minecraft keeps reloading at the initial loading

**Comment by tr7zw** [comment]
Log?

**Comment by Imayreportbugs** [comment]
[latest.log](https://github.com/tr7zw/WaveyCapes/files/7093816/latest.log)

**Comment by Imayreportbugs** [comment]
it s incompatible with one of my mods( apart from Minecraft capes mod)?

**Comment by tr7zw** [comment]
I'll have to to give it a try myself. But the Minecraft capes mod sounds like a possible cause? The odd thing is that there is no error in the log.

**Comment by Imayreportbugs** [comment]
someone had a similar error with all of fabric 3 a bunch of time ago 
they fixed it by installing indium but for my case it wont work

**Comment by tr7zw** [comment]
Recreated the setup and:
` java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Failed to create model for minecraft:piglin
	[...]
Caused by: java.lang.IllegalArgumentException: Failed to create model for minecraft:piglin
	at net.minecraft.class_5619.method_32174(class_5619.java:153) ~[intermediary-1.17.1.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:149) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:369) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 104 more
Caused by: java.util.NoSuchElementException: Can't find part customCape_0
	at net.minecraft.class_630.method_32086(class_630.java:60) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_591.handler$zgp000$onCreate(class_591.java:1535) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_591.<init>(class_591.java:54) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4840.<init>(class_4840.java:27) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4842.method_24875(class_4842.java:36) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4842.<init>(class_4842.java:27) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.method_32185(class_5619.java:96) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.redirect$zfd000$createEntityRenderer(class_5619.java:559) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_5619.method_32174(class_5619.java:151) ~[intermediary-1.17.1.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1425) ~[?:?]
	at net.minecraft.class_5619.method_32176(class_5619.java:149) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_898.method_14491(class_898.java:369) ~[intermediary-1.17.1.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-1.17.1.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 104 more`

So somehow it tries to find the cape the Piglin model?!? Not sure yet why tho.

**Comment by Imayreportbugs** [comment]
Should I report this bug on the minecraft cape mod?
But I can t find the github page

**Comment by tr7zw** [comment]
I'm testing rn what is causing it exactly. And I can add a workaround for it.

**Comment by tr7zw** [comment]
Yea its the Minecraft cape mod. I'll try to add a workaround.

**Comment by tr7zw** [comment]
Hm then there isn't that much I can do. The mod isn't open source so I cant check directly what its even doing, but it probably creates a custom cape instead of using the vanilla one. You can look into the mods Fabric Capes or Kappa to get capes that are better compatible with other mods like this.
