### ISSUE TITLE
MinecraftCapes crash

### ISSUE THREAD

**Issue by james090500** [tr7zw/WaveyCapes#42]
Hi,

With the newest build of MinecraftCapes on 1.19 and 1.18 some methods have been renamed causing a crash .

`PlayerHandler.getFromPlayer` is now just `PlayerHandler.get`

```
java.lang.NoSuchMethodError: 'net.minecraftcapes.player.PlayerHandler net.minecraftcapes.player.PlayerHandler.getFromPlayer(net.minecraft.class_1657)'
	at dev.tr7zw.waveycapes.support.MinecraftCapesSupport.shouldBeUsed(MinecraftCapesSupport.java:24)
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.getCapeRenderer(CustomCapeRenderLayer.java:483)
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.render(CustomCapeRenderLayer.java:70)
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.method_4199(CustomCapeRenderLayer.java:41)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:66)
	at net.minecraft.class_1007.method_3936(class_1007.java:43)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1572)
	at net.minecraft.class_761.method_22710(class_761.java:1322)
	at net.minecraft.class_757.method_3188(class_757.java:1100)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by james090500** [comment]
This is affect 1.18.2 as well.

**Comment by tr7zw** [comment]
Fixed for 1.19.3/4. Will do 1.18 later.

**Comment by KrazyGateKeeper** [comment]
1.19.2 is also affected. please fix.

**Comment by tr7zw** [comment]
Honestly, people need to stop using 1.19.1/2/3. Will look into it when looking into 1.18.

**Comment by james090500** [comment]
> Honestly, people need to stop using 1.19.1/2/3. Will look into it when looking into 1.18.

Trust me, I've tried this battle with MinecraftCapes but you'd be surprised how many people use unsupported minor versions.

**Comment by james090500** [comment]
I've re-added `getFromPlayer` as a deprecated function in all version from 1.18.2 to 1.20.1 (which it was removed from). This should prevent this from happening.

**Comment by tr7zw** [comment]
Probably wasn't needed for 1.19.3-1.20.1. Didn't know you're the dev, what even was the reason for this change, and why doesn't the Minecraft Capes mod use the normal cape logic like FabricCapes/Optifine? Then this wouldn't have been an issue in the first place(and would reduce the amount of duplicated vanilla code in your mod).
